name       : python-sqlalchemy
version    : 1.1.2
release    : 2
source     :
    - https://pypi.python.org/packages/44/88/a86ba3fddb1fd7fc2c271355fc11e5f50634e30a0859ccc613fe62973a98/SQLAlchemy-1.1.2.tar.gz : 1692c35bc0f7026d20cabd43b0f6f265e855129f44eb4574fea361e3c5cc89a5
license    : MIT
component  : programming.python
summary    : The Python SQL Toolkit and Object Relational Mapper
description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
    SQLAlchemy provides a full suite of well known enterprise-level persistence patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
