name       : python-sqlalchemy
version    : 1.2.16
release    : 6
source     :
    - https://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-1.2.16.tar.gz : 6af3ca2f7f00844465ab4fa78337d487b39e53f516c51328aed4ed3a719d4264
license    : MIT
component  : programming.python
summary    : The Python SQL Toolkit and Object Relational Mapper
description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
    SQLAlchemy provides a full suite of well known enterprise-level persistence patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -k 'not test_tutorials'
    %python3_test py.test3 -k 'not test_tutorials'
