name       : python-sqlalchemy
version    : 1.2.14
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/S/SQLAlchemy/SQLAlchemy-1.2.14.tar.gz : 9de7c7dabcf06319becdb7e15099c44e5e34ba7062f9ba10bc00e562f5db3d04
license    : MIT
component  : programming.python
summary    : The Python SQL Toolkit and Object Relational Mapper
description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
    SQLAlchemy provides a full suite of well known enterprise-level persistence patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -k 'not test_tutorials'
    %python3_test py.test3 -k 'not test_tutorials'
