name       : python-sqlalchemy
version    : 1.3.23
release    : 15
source     :
    - https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-1.3.23.tar.gz : 6fca33672578666f657c131552c4ef8979c1606e494f78cd5199742dfb26918b
license    : MIT
component  : programming.python
summary    : The Python SQL Toolkit and Object Relational Mapper
description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
    SQLAlchemy provides a full suite of well known enterprise-level persistence patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # requires pytest-xdist.
#    %python3_test
