name       : python-sqlalchemy
version    : 1.3.10
release    : 10
source     :
    - https://files.pythonhosted.org/packages/14/0e/487f7fc1e432cec50d2678f94e4133f2b9e9356e35bacc30d73e8cb831fc/SQLAlchemy-1.3.10.tar.gz : 0f0768b5db594517e1f5e1572c73d14cf295140756431270d89496dc13d5e46c
license    : MIT
component  : programming.python
summary    : The Python SQL Toolkit and Object Relational Mapper
description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
    SQLAlchemy provides a full suite of well known enterprise-level persistence patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    # requires pytest-xdist.
#    %python_test
#    %python3_test
