name       : python-sqlalchemy
version    : 1.3.3
release    : 8
source     :
    - https://github.com/sqlalchemy/sqlalchemy/archive/rel_1_3_3.tar.gz : 7d11d3ef348cbc9444fb1ed4c930f8ab1cb2c974960e95fd3b6c075cfff20a3f
license    : MIT
component  : programming.python
summary    : The Python SQL Toolkit and Object Relational Mapper
description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
    SQLAlchemy provides a full suite of well known enterprise-level persistence patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -k 'not test_tutorials'
    %python3_test py.test3 -k 'not test_tutorials'
